/** Public markdown + PDF catalog for the in-site viewer. */
export const DOC_CATEGORIES = [
  { id: 'tutorial', label: 'Tutorial', color: '#c43c24' },
  { id: 'demo', label: 'Demostración', color: '#2a7a4b' },
  { id: 'bench', label: 'Benchmarks', color: '#b58900' },
  { id: 'theory', label: 'Teoría', color: '#3d5a99' },
  { id: 'research', label: 'Investigación', color: '#7a3d8c' },
  { id: 'impl', label: 'Implementación', color: '#1a6b7a' },
  { id: 'wsp', label: 'RogexWSP', color: '#c45c14' },
  { id: 'prisma', label: 'PRISMA', color: '#8b3a4a' },
  { id: 'navi', label: 'NAVI', color: '#2a5a8c' },
];

export const DOCS = [
  {
    id: 'tutorial-monad',
    title: 'Tutorial rxOS 9 SMOKE',
    category: 'tutorial',
    path: '/docs/rxos/tutorial-monad.md',
    blurb: 'Arrancar la ISO 9, tecla v, Navi 7, /prove, cómo medir.',
  },
  {
    id: 'isos',
    title: 'Dónde están las ISOs — rxOS 9',
    category: 'tutorial',
    path: '/docs/rxos/ISOS.md',
    blurb: 'VM para QEMU, metal para USB. SHA-256 de 9.0.0 y cómo flashear.',
  },
  {
    id: 'rxos9',
    title: 'rxOS 9 SMOKE — qué es',
    category: 'tutorial',
    path: '/docs/rxos/RXOS9.md',
    blurb: 'Unikernel Dark Aero, NAVI 7, wget, Photos. El producto de hoy.',
  },
  {
    id: 'rxos8',
    title: 'rxOS 8 DESKTOP — historia',
    category: 'tutorial',
    path: '/docs/rxos/RXOS8.md',
    blurb: 'Lo que era 8.x. El producto de hoy es 9 SMOKE.',
  },
  {
    id: 'navi-catalog',
    title: 'Catálogo NAVI 1 → 7',
    category: 'navi',
    path: '/docs/navi/CATALOG.md',
    blurb: 'Línea SNN. 7-WORLD es oficial en rxOS 9. 7-NPU (Akida) sigue PLAN.',
  },
  {
    id: 'navi-compare',
    title: 'NAVI frente a otras IA neuromórficas',
    category: 'theory',
    path: '/docs/navi/NAVI_COMPARE.md',
    blurb: 'Loihi, Akida, SpiNNaker, TrueNorth, LLMs. Qué somos y qué no. Para escépticos.',
  },
  {
    id: 'resumen-tecnico',
    title: 'Resumen técnico — lab, web, rxOS, NAVI',
    category: 'theory',
    path: '/docs/rxos/RESUMEN_TECNICO.md',
    blurb: 'Qué dice la web, qué hay en el binario, Q₆, WSP, RX-DIB, estado de la empresa, qué falta y qué sigue.',
  },
  {
    id: 'eternal-eclipse',
    title: 'Eternal Eclipse — hoja de ruta pública',
    category: 'theory',
    path: '/docs/rxos/ETERNAL_ECLIPSE.md',
    blurb: 'Dónde estamos de verdad: 8.5/6.5 medido, 9/7-WORLD en curso. 10/10 es el Eclipse. EchOS es visión.',
  },
  {
    id: 'cianotipo',
    title: 'Cianotipo — rxOS, NAVI, PRISMA, Akida',
    category: 'theory',
    path: '/docs/rxos/CIANOTIPO.md',
    blurb: 'Qué corre, qué está dibujado, qué espera a una placa. Nivel 3 = objetivo.',
  },
  {
    id: 'cianotipo-dummies',
    title: 'Cianotipo para dummies',
    category: 'tutorial',
    path: '/docs/rxos/CIANOTIPO_DUMMIES.md',
    blurb: 'Tres máquinas, un idioma. NAVI 7-WORLD ya corre en rxOS 9. El NPU sigue PLAN.',
  },
  {
    id: 'akida',
    title: 'Akida × rxOS — el gancho',
    category: 'impl',
    path: '/docs/navi/AKIDA.md',
    blurb: 'MetaTF 2.19, Engine C++, HardwareDriver, cinco cerraduras. Sin placa.',
  },
  {
    id: 'navi7',
    title: 'NAVI 7 — 7-WORLD oficial',
    category: 'navi',
    path: '/docs/navi/NAVI7.md',
    blurb: 'Oficial en rxOS 9: catálogo + harvest. 7-NPU Akida sigue PLAN. Sin ficha: DESCONOCIDO.',
  },
  {
    id: 'navi75',
    title: 'NAVI 7.5 — asistente con memoria',
    category: 'navi',
    path: '/docs/navi/NAVI75.md',
    blurb: 'Voz humana, SQLite, Wikipedia/DuckDuckGo. No es un LLM.',
  },
  {
    id: 'setup',
    title: 'Arrancar rxOS 9 — QEMU, VirtualBox, USB',
    category: 'tutorial',
    path: '/docs/rxos/SETUP.md',
    blurb: 'Tres caminos de 2 minutos. ISO VM o metal. NAVI 7.5 en el host.',
  },
  {
    id: 'navi66',
    title: 'NAVI 6.6 — lengua + TUI',
    category: 'navi',
    path: '/docs/navi/NAVI66.md',
    blurb: 'Articulos, tiempos, corrector que supone. TUI de colores. No es un LLM.',
  },
  {
    id: 'navi66-dummies',
    title: 'NAVI 6.6 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI66_DUMMIES.md',
    blurb: 'Si escribes «kien», lo marca y supone «quien».',
  },
  {
    id: 'navi66-experts',
    title: 'NAVI 6.6 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI66_EXPERTS.md',
    blurb: 'Léxico cerrado, Damerau, ratatui / ANSI / pthread.',
  },
  {
    id: 'navi65',
    title: 'NAVI 6.5 — RLC',
    category: 'navi',
    path: '/docs/navi/NAVI65.md',
    blurb: 'Once máscaras G_*. PARSE-RETRIEVE-INFER-VERIFY-RENDER. No es un LLM.',
  },
  {
    id: 'navi65-dummies',
    title: 'NAVI 6.5 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI65_DUMMIES.md',
    blurb: 'Once relés, no un loro. Cinco cajas. DESCONOCIDO si no hay ficha.',
  },
  {
    id: 'navi65-experts',
    title: 'NAVI 6.5 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI65_EXPERTS.md',
    blurb: 'Hook del kernel, math entero, catálogo de código, reflect().',
  },
  {
    id: 'navi6',
    title: 'NAVI 6 — tutor causal',
    category: 'navi',
    path: '/docs/navi/NAVI6.md',
    blurb: 'DAG + world-model + neurogénesis. G_debug de 6.5. No es un LLM ni un QPU.',
  },
  {
    id: 'navi6-dummies',
    title: 'NAVI 6 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI6_DUMMIES.md',
    blurb: 'El mecánico, no el loro. Analogía de un minuto.',
  },
  {
    id: 'navi6-experts',
    title: 'NAVI 6 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI6_EXPERTS.md',
    blurb: 'Blob NAVI6W01, do-calculus, hook del kernel, cómo medir.',
  },
  {
    id: 'navi1',
    title: 'NAVI 1 — Q₆ L1',
    category: 'navi',
    path: '/docs/navi/NAVI1.md',
    blurb: 'Hipercubo de 6 bits. 48/48. No habla.',
  },
  {
    id: 'navi5',
    title: 'NAVI 5 — lab cooperativo',
    category: 'navi',
    path: '/docs/navi/NAVI5.md',
    blurb: 'KCC, LIF+STDP, WSP 16 B, air-gap. No es un LLM.',
  },
  {
    id: 'navi5-arch',
    title: 'NAVI 5 — arquitectura',
    category: 'navi',
    path: '/docs/navi/NAVI5_ARCHITECTURE.md',
    blurb: 'Harness pasivo, RX-DIB, Q6, Docker network none.',
  },
  {
    id: 'navi5-train',
    title: 'NAVI 5 — entrenamiento',
    category: 'navi',
    path: '/docs/navi/NAVI5_TRAINING.md',
    blurb: 'Seis fases. Cero pruning. Resultados medidos.',
  },
  {
    id: 'navi45',
    title: 'NAVI-4.5 — el operador',
    category: 'navi',
    path: '/docs/rxos/NAVI45.md',
    blurb: 'WSP 16 B, G_rxos, /prove. No es un LLM.',
  },
  {
    id: 'user-notice',
    title: 'Aviso NAVI 7 — qué esperar',
    category: 'tutorial',
    path: '/docs/rxos/USER_NOTICE.md',
    blurb: 'No es un LLM. 73 fichas. Sin ficha: DESCONOCIDO.',
  },
  {
    id: 'para-curiosos',
    title: 'rxOS 9 para curiosos',
    category: 'demo',
    path: '/docs/rxos/para-curiosos.md',
    blurb: 'Tres minutos. Arrancas, pulsas v, preguntas.',
  },
  {
    id: 'demostracion',
    title: 'Demostración y benches rxOS 9',
    category: 'demo',
    path: '/docs/rxos/demostracion.md',
    blurb: '9 SMOKE + RAPL metal 8.5. Capturas QEMU reales.',
  },
  {
    id: 'monad-demo',
    title: 'Spec de demo dual',
    category: 'demo',
    path: '/docs/rxos/MONAD-DEMO.md',
    blurb: 'Público curioso + métricas para quien mide.',
  },
  {
    id: 'hp-metal-85',
    title: 'HP 15-ac195nl — metal 8.5 medido',
    category: 'bench',
    path: '/docs/rxos/HP_AC195NL_85.md',
    blurb: 'RAPL, navi3/navi6, 72.5 µJ/run Q6. Ocho fotos del portátil, 17 ago 2026.',
  },
  {
    id: 'measure',
    title: 'MEASURE — cómo medir Q₆ / L2',
    category: 'bench',
    path: '/docs/navi/MEASURE.md',
    blurb: 'Protocolo de medida del banco host NAVI. Metal: /docs/hp-metal-85.',
  },
  {
    id: 'l2',
    title: 'NAVI L2 — HDC + RWKV',
    category: 'bench',
    path: '/docs/navi/L2.md',
    blurb: '66 352 B planos, leaky 7:1, no es un LLM.',
  },
  {
    id: 'l3',
    title: 'NAVI L3 — entrenar el SLM',
    category: 'bench',
    path: '/docs/navi/L3.md',
    blurb: 'train.py → navi2_weights.bin, sin Hugging Face.',
  },
  {
    id: 'rfc-q6',
    title: 'RFC-2026-08-Q6 — PoC medido',
    category: 'theory',
    path: '/docs/navi/RFC-2026-08-Q6.md',
    blurb: 'Hipercubo Q₆, Hamming, codebook [6,3,3]. Lo que ya corre.',
  },
  {
    id: 'rfc-q6-campana',
    title: 'RFC-2026-08-Q6 — campaña abierta',
    category: 'research',
    path: '/docs/navi/RFC-2026-08-Q6-CAMPANA.md',
    pdf: '/docs/navi/RFC-2026-08-Q6_CAMPANA.pdf',
    blurb: 'Convocatoria: hipótesis Q₆, fases, KPI y dónde enviar resultados.',
  },
  {
    id: 'manifesto',
    title: 'Manifiesto neuromórfico',
    category: 'theory',
    path: '/docs/rxos/neuromorphic_manifesto.md',
    blurb: 'Eventos, LIF entero, límites del slogan.',
  },
  {
    id: 'event-fabric',
    title: 'Event fabric',
    category: 'theory',
    path: '/docs/rxos/event_fabric.md',
    blurb: 'Anillos SPSC, actores blandos, Q16.16.',
  },
  {
    id: 'monad',
    title: 'rxOS MONAD — mapa de código',
    category: 'research',
    path: '/docs/rxos/MONAD.md',
    blurb: 'Dónde está el código y cómo comprobarlo.',
  },
  {
    id: 'navi3',
    title: 'NAVI-3/4 WSP — arquitectura',
    category: 'navi',
    path: '/docs/rxos/NAVI3_WSP_ARCHITECTURE.md',
    blurb: 'Transductor S→S′, 16 B, máscara ES, ext v0.5.',
  },
  {
    id: 'navi2',
    title: 'NAVI 2 — arquitectura (legado ASCII)',
    category: 'navi',
    path: '/docs/rxos/NAVI2_ARCHITECTURE.md',
    blurb: 'Motor de bytes legado. El chat del ISO usa NAVI-3.',
  },
  {
    id: 'kernel-navi',
    title: 'kernel/navi README',
    category: 'impl',
    path: '/docs/navi/kernel.md',
    blurb: 'Actor blando Q₆ en el unikernel.',
  },
  {
    id: 'prisma-engine',
    title: 'PRISMA Engine técnico',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_ENGINE_TECHNICAL.md',
    blurb: 'Runtime Rust: SPSC, Δ-mod, LIF AVX2.',
  },
  {
    id: 'prisma5-snn',
    title: 'PRISMA 5 SNN',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_SNN_TECHNICAL.md',
    blurb: 'Producto SNN event-driven (sin descarga P5).',
  },
  {
    id: 'prisma5-roadmap',
    title: 'PRISMA 5 roadmap',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_ROADMAP.md',
    blurb: 'Fases α → 1.0 y gates de release.',
  },
  {
    id: 'wsp-readme',
    title: 'RogexWSP — protocolo',
    category: 'wsp',
    path: '/docs/wsp/README.md',
    blurb: 'Un núcleo de significado, muchas máscaras. Repo navywakura/RogexWSP.',
  },
  {
    id: 'wsp-philosophy',
    title: 'RogexWSP — filosofía',
    category: 'wsp',
    path: '/docs/wsp/PHILOSOPHY.md',
    blurb: 'I+E→S. La palabra es solo una máscara.',
  },
  {
    id: 'wsp-spec',
    title: 'RogexWSP — SPEC v0.1',
    category: 'wsp',
    path: '/docs/wsp/SPEC.md',
    blurb: '32 átomos, 6 ejes, JSON y binario normativo.',
  },
  {
    id: 'wsp-binary',
    title: 'RogexWSP — formato binario',
    category: 'wsp',
    path: '/docs/wsp/BINARY_FORMAT.md',
    blurb: 'Magic WSP, flags, átomos 5-bit, emoción i8.',
  },
  {
    id: 'wsp-snippets',
    title: 'RogexWSP — snippets',
    category: 'wsp',
    path: '/docs/wsp/SNIPPETS.md',
    blurb: 'primitives, Emotion, Symbol, encode/decode. Código real.',
  },
];

export function catById(id) {
  return DOC_CATEGORIES.find((c) => c.id === id) || null;
}

export function docById(id) {
  return DOCS.find((d) => d.id === id) || null;
}

export function docByPath(pathname) {
  const clean = pathname.replace(/\/+$/, '');
  return DOCS.find((d) => d.path.replace(/\.md$/, '') === clean || d.path === clean) || null;
}
