/** Public markdown + PDF catalog for the in-site viewer. */
export const DOC_CATEGORIES = [
  { id: 'tutorial', label: 'Tutorial', color: '#c43c24' },
  { id: 'demo', label: 'Demostración', color: '#2a7a4b' },
  { id: 'bench', label: 'Benchmarks', color: '#b58900' },
  { id: 'theory', label: 'Teoría', color: '#3d5a99' },
  { id: 'research', label: 'Investigación', color: '#7a3d8c' },
  { id: 'impl', label: 'Implementación', color: '#1a6b7a' },
  { id: 'wsp', label: 'RogexWSP', color: '#c45c14' },
  { id: 'prisma', label: 'PRISMA', color: '#8b3a4a' },
  { id: 'navi', label: 'NAVI', color: '#2a5a8c' },
];

export const DOCS = [
  {
    id: 'tutorial-monad',
    title: 'Tutorial rxOS 8 DESKTOP',
    category: 'tutorial',
    path: '/docs/rxos/tutorial-monad.md',
    blurb: 'Arrancar la ISO 8, tecla v, /prove, cómo medir.',
  },
  {
    id: 'rxos8',
    title: 'rxOS 8 DESKTOP — qué es',
    category: 'tutorial',
    path: '/docs/rxos/RXOS8.md',
    blurb: 'Unikernel, números comprobables, historia de versiones.',
  },
  {
    id: 'navi-catalog',
    title: 'Catálogo NAVI 1 → 6.5',
    category: 'navi',
    path: '/docs/navi/CATALOG.md',
    blurb: 'Línea SNN completa. 6.5 es el RLC oficial. 7 es plan (Akida).',
  },
  {
    id: 'cianotipo',
    title: 'Cianotipo — rxOS, NAVI, PRISMA, Akida',
    category: 'theory',
    path: '/docs/rxos/CIANOTIPO.md',
    blurb: 'Qué corre, qué está dibujado, qué espera a una placa. Nivel 3 = objetivo.',
  },
  {
    id: 'cianotipo-dummies',
    title: 'Cianotipo para dummies',
    category: 'tutorial',
    path: '/docs/rxos/CIANOTIPO_DUMMIES.md',
    blurb: 'Tres máquinas, un idioma. NAVI 7 no está escrito.',
  },
  {
    id: 'akida',
    title: 'Akida × rxOS — el gancho',
    category: 'impl',
    path: '/docs/navi/AKIDA.md',
    blurb: 'MetaTF 2.19, Engine C++, HardwareDriver, cinco cerraduras. Sin placa.',
  },
  {
    id: 'navi7',
    title: 'NAVI 7 — plan',
    category: 'navi',
    path: '/docs/navi/NAVI7.md',
    blurb: '6.5 + NPU. Criterios para atreverse a llamar 7 a un commit. No hay código.',
  },
  {
    id: 'navi65',
    title: 'NAVI 6.5 — RLC',
    category: 'navi',
    path: '/docs/navi/NAVI65.md',
    blurb: 'Once máscaras G_*. PARSE-RETRIEVE-INFER-VERIFY-RENDER. No es un LLM.',
  },
  {
    id: 'navi65-dummies',
    title: 'NAVI 6.5 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI65_DUMMIES.md',
    blurb: 'Once relés, no un loro. Cinco cajas. DESCONOCIDO si no hay ficha.',
  },
  {
    id: 'navi65-experts',
    title: 'NAVI 6.5 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI65_EXPERTS.md',
    blurb: 'Hook del kernel, math entero, catálogo de código, reflect().',
  },
  {
    id: 'navi6',
    title: 'NAVI 6 — tutor causal',
    category: 'navi',
    path: '/docs/navi/NAVI6.md',
    blurb: 'DAG + world-model + neurogénesis. G_debug de 6.5. No es un LLM ni un QPU.',
  },
  {
    id: 'navi6-dummies',
    title: 'NAVI 6 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI6_DUMMIES.md',
    blurb: 'El mecánico, no el loro. Analogía de un minuto.',
  },
  {
    id: 'navi6-experts',
    title: 'NAVI 6 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI6_EXPERTS.md',
    blurb: 'Blob NAVI6W01, do-calculus, hook del kernel, cómo medir.',
  },
  {
    id: 'navi1',
    title: 'NAVI 1 — Q₆ L1',
    category: 'navi',
    path: '/docs/navi/NAVI1.md',
    blurb: 'Hipercubo de 6 bits. 48/48. No habla.',
  },
  {
    id: 'navi5',
    title: 'NAVI 5 — lab cooperativo',
    category: 'navi',
    path: '/docs/navi/NAVI5.md',
    blurb: 'KCC, LIF+STDP, WSP 16 B, air-gap. No es un LLM.',
  },
  {
    id: 'navi5-arch',
    title: 'NAVI 5 — arquitectura',
    category: 'navi',
    path: '/docs/navi/NAVI5_ARCHITECTURE.md',
    blurb: 'Harness pasivo, RX-DIB, Q6, Docker network none.',
  },
  {
    id: 'navi5-train',
    title: 'NAVI 5 — entrenamiento',
    category: 'navi',
    path: '/docs/navi/NAVI5_TRAINING.md',
    blurb: 'Seis fases. Cero pruning. Resultados medidos.',
  },
  {
    id: 'navi45',
    title: 'NAVI-4.5 — el operador',
    category: 'navi',
    path: '/docs/rxos/NAVI45.md',
    blurb: 'WSP 16 B, G_rxos, /prove. No es un LLM.',
  },
  {
    id: 'user-notice',
    title: 'Aviso NAVI-4.5 — qué esperar',
    category: 'tutorial',
    path: '/docs/rxos/USER_NOTICE.md',
    blurb: 'Habla WSP. El castellano es máscara. Lista blanca.',
  },
  {
    id: 'para-curiosos',
    title: 'rxOS 8 para curiosos',
    category: 'demo',
    path: '/docs/rxos/para-curiosos.md',
    blurb: 'Tres minutos, capturas reales, cero teatro.',
  },
  {
    id: 'demostracion',
    title: 'Demostración y benches rxOS 8',
    category: 'demo',
    path: '/docs/rxos/demostracion.md',
    blurb: 'QEMU, /prove, Q₆, capturas 11–17 del 13 ago 2026.',
  },
  {
    id: 'monad-demo',
    title: 'Spec de demo dual',
    category: 'demo',
    path: '/docs/rxos/MONAD-DEMO.md',
    blurb: 'Público curioso + métricas para quien mide.',
  },
  {
    id: 'measure',
    title: 'MEASURE — cómo medir Q₆ / L2',
    category: 'bench',
    path: '/docs/navi/MEASURE.md',
    blurb: 'Protocolo de medida del banco host NAVI.',
  },
  {
    id: 'l2',
    title: 'NAVI L2 — HDC + RWKV',
    category: 'bench',
    path: '/docs/navi/L2.md',
    blurb: '66 352 B planos, leaky 7:1, no es un LLM.',
  },
  {
    id: 'l3',
    title: 'NAVI L3 — entrenar el SLM',
    category: 'bench',
    path: '/docs/navi/L3.md',
    blurb: 'train.py → navi2_weights.bin, sin Hugging Face.',
  },
  {
    id: 'rfc-q6',
    title: 'RFC-2026-08-Q6 — PoC medido',
    category: 'theory',
    path: '/docs/navi/RFC-2026-08-Q6.md',
    blurb: 'Hipercubo Q₆, Hamming, codebook [6,3,3]. Lo que ya corre.',
  },
  {
    id: 'rfc-q6-campana',
    title: 'RFC-2026-08-Q6 — campaña abierta',
    category: 'research',
    path: '/docs/navi/RFC-2026-08-Q6-CAMPANA.md',
    pdf: '/docs/navi/RFC-2026-08-Q6_CAMPANA.pdf',
    blurb: 'Convocatoria: hipótesis Q₆, fases, KPI y dónde enviar resultados.',
  },
  {
    id: 'manifesto',
    title: 'Manifiesto neuromórfico',
    category: 'theory',
    path: '/docs/rxos/neuromorphic_manifesto.md',
    blurb: 'Eventos, LIF entero, límites del slogan.',
  },
  {
    id: 'event-fabric',
    title: 'Event fabric',
    category: 'theory',
    path: '/docs/rxos/event_fabric.md',
    blurb: 'Anillos SPSC, actores blandos, Q16.16.',
  },
  {
    id: 'monad',
    title: 'rxOS MONAD — mapa de código',
    category: 'research',
    path: '/docs/rxos/MONAD.md',
    blurb: 'Dónde está el código y cómo comprobarlo.',
  },
  {
    id: 'navi3',
    title: 'NAVI-3/4 WSP — arquitectura',
    category: 'navi',
    path: '/docs/rxos/NAVI3_WSP_ARCHITECTURE.md',
    blurb: 'Transductor S→S′, 16 B, máscara ES, ext v0.5.',
  },
  {
    id: 'navi2',
    title: 'NAVI 2 — arquitectura (legado ASCII)',
    category: 'navi',
    path: '/docs/rxos/NAVI2_ARCHITECTURE.md',
    blurb: 'Motor de bytes legado. El chat del ISO usa NAVI-3.',
  },
  {
    id: 'kernel-navi',
    title: 'kernel/navi README',
    category: 'impl',
    path: '/docs/navi/kernel.md',
    blurb: 'Actor blando Q₆ en el unikernel.',
  },
  {
    id: 'prisma-engine',
    title: 'PRISMA Engine técnico',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_ENGINE_TECHNICAL.md',
    blurb: 'Runtime Rust: SPSC, Δ-mod, LIF AVX2.',
  },
  {
    id: 'prisma5-snn',
    title: 'PRISMA 5 SNN',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_SNN_TECHNICAL.md',
    blurb: 'Producto SNN event-driven (sin descarga P5).',
  },
  {
    id: 'prisma5-roadmap',
    title: 'PRISMA 5 roadmap',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_ROADMAP.md',
    blurb: 'Fases α → 1.0 y gates de release.',
  },
  {
    id: 'wsp-readme',
    title: 'RogexWSP — protocolo',
    category: 'wsp',
    path: '/docs/wsp/README.md',
    blurb: 'Un núcleo de significado, muchas máscaras. Repo navywakura/RogexWSP.',
  },
  {
    id: 'wsp-philosophy',
    title: 'RogexWSP — filosofía',
    category: 'wsp',
    path: '/docs/wsp/PHILOSOPHY.md',
    blurb: 'I+E→S. La palabra es solo una máscara.',
  },
  {
    id: 'wsp-spec',
    title: 'RogexWSP — SPEC v0.1',
    category: 'wsp',
    path: '/docs/wsp/SPEC.md',
    blurb: '32 átomos, 6 ejes, JSON y binario normativo.',
  },
  {
    id: 'wsp-binary',
    title: 'RogexWSP — formato binario',
    category: 'wsp',
    path: '/docs/wsp/BINARY_FORMAT.md',
    blurb: 'Magic WSP, flags, átomos 5-bit, emoción i8.',
  },
  {
    id: 'wsp-snippets',
    title: 'RogexWSP — snippets',
    category: 'wsp',
    path: '/docs/wsp/SNIPPETS.md',
    blurb: 'primitives, Emotion, Symbol, encode/decode. Código real.',
  },
];

export function catById(id) {
  return DOC_CATEGORIES.find((c) => c.id === id) || null;
}

export function docById(id) {
  return DOCS.find((d) => d.id === id) || null;
}

export function docByPath(pathname) {
  const clean = pathname.replace(/\/+$/, '');
  return DOCS.find((d) => d.path.replace(/\.md$/, '') === clean || d.path === clean) || null;
}
