/** Public markdown + PDF catalog for the in-site viewer. */
export const DOC_CATEGORIES = [
  { id: 'tutorial', label: 'Tutorial', labelEn: 'Tutorial', color: '#c43c24' },
  { id: 'demo', label: 'Demostración', labelEn: 'Demo', color: '#2a7a4b' },
  { id: 'bench', label: 'Benchmarks', labelEn: 'Benchmarks', color: '#b58900' },
  { id: 'theory', label: 'Teoría', labelEn: 'Theory', color: '#3d5a99' },
  { id: 'research', label: 'Investigación', labelEn: 'Research', color: '#7a3d8c' },
  { id: 'impl', label: 'Implementación', labelEn: 'Implementation', color: '#1a6b7a' },
  { id: 'wsp', label: 'RogexWSP', labelEn: 'RogexWSP', color: '#c45c14' },
  { id: 'prisma', label: 'PRISMA', labelEn: 'PRISMA', color: '#8b3a4a' },
  { id: 'navi', label: 'NAVI', labelEn: 'NAVI', color: '#2a5a8c' },
];

export const DOCS = [
  {
    id: 'diario',
    title: 'Cuaderno de laboratorio',
    titleEn: 'Lab notebook',
    category: 'theory',
    path: '/docs/rxos/DIARIO.md',
    pathEn: '/docs/rxos/DIARIO.en.md',
    blurb: 'NAVI 10 ya corre. rxOS 10 es el siguiente. EchOS: el 10 con Echo dentro. La seguiremos entrenando.',
    blurbEn: 'NAVI 10 already runs. rxOS 10 is next. EchOS: 10 with Echo inside. We will keep training it.',
    date: '2026-08-20',
    diary: true,
  },
  {
    id: 'navi10-spec',
    title: 'Ficha NAVI 10 + rxOS 10',
    titleEn: 'NAVI 10 + rxOS 10 product sheet',
    category: 'navi',
    path: '/docs/navi/NAVI10_SPEC.md',
    pathEn: '/docs/navi/NAVI10_SPEC.en.md',
    blurb: 'Propiedades, SKU, VERIFY, Q_N, CAM. Host live / ISO 10 próximo. Sin cifras inventadas.',
    blurbEn: 'Properties, SKU, VERIFY, Q_N, CAM. Host live / ISO 10 coming soon. No invented figures.',
    date: '2026-08-20',
  },
  {
    id: 'navi10',
    title: 'NAVI 10 — Echo Heap-0',
    titleEn: 'NAVI 10 — Echo Heap-0',
    category: 'navi',
    path: '/docs/navi/NAVI10.md',
    pathEn: '/docs/navi/NAVI10.en.md',
    blurb: 'SNN host LIVE. Q_N = Q₈×Q₈, CAM 4096×32 B, VERIFY o DESCONOCIDO. Akida PLAN. No es un LLM.',
    blurbEn: 'SNN host LIVE. Q_N = Q₈×Q₈, CAM 4096×32 B, VERIFY or UNKNOWN. Akida PLAN. Not an LLM.',
    date: '2026-08-20',
  },
  {
    id: 'rxos10',
    title: 'rxOS 10 — próximo lanzamiento',
    titleEn: 'rxOS 10 — coming soon',
    category: 'tutorial',
    path: '/docs/rxos/RXOS10.md',
    pathEn: '/docs/rxos/RXOS10.en.md',
    blurb: 'El Eclipse: unikernel + Echo. No hay ISO 10. Hoy se descarga 9.0.0 SMOKE. Contrato, no binario.',
    blurbEn: 'The Eclipse: unikernel + Echo. No ISO 10 yet. Today you download 9.0.0 SMOKE. Contract, not a binary.',
    date: '2026-08-20',
  },
  {
    id: 'navi10-lpu',
    title: 'NAVI 10 — LPU (córtex verbal)',
    titleEn: 'NAVI 10 — LPU (verbal cortex)',
    category: 'navi',
    path: '/docs/navi/NAVI10_LPU.md',
    pathEn: '/docs/navi/NAVI10_LPU.en.md',
    blurb: 'La boca no posee los hechos. Relación y metáfora sí; masa de un asteroide, no.',
    blurbEn: 'The mouth does not own facts. Relation and metaphor yes; an asteroid’s mass, no.',
    date: '2026-08-20',
  },
  {
    id: 'navi10-ship',
    title: 'NAVI 10 — empaque USB / SKU',
    titleEn: 'NAVI 10 — USB / SKU packing',
    category: 'impl',
    path: '/docs/navi/NAVI10_SHIP.md',
    pathEn: '/docs/navi/NAVI10_SHIP.en.md',
    blurb: 'Pequeño en el producto. Wiki dump opcional. Sin PyTorch ni Piper en el USB.',
    blurbEn: 'Small in the product. Optional wiki dump. No PyTorch or Piper on the USB.',
    date: '2026-08-20',
  },
  {
    id: 'navi10-train',
    title: 'NAVI 10 — entrenar (sin backprop)',
    titleEn: 'NAVI 10 — train (no backprop)',
    category: 'tutorial',
    path: '/docs/navi/NAVI10_TRAIN.md',
    pathEn: '/docs/navi/NAVI10_TRAIN.en.md',
    blurb: 'Atractores en Q_N + CAM. Cuatro métodos. destroyed=0. --train es falseable.',
    blurbEn: 'Attractors on Q_N + CAM. Four methods. destroyed=0. --train is falsifiable.',
    date: '2026-08-20',
  },
  {
    id: 'navi10-meta',
    title: 'NAVI 10 — metacognición',
    titleEn: 'NAVI 10 — metacognition',
    category: 'navi',
    path: '/docs/navi/NAVI10_META.md',
    pathEn: '/docs/navi/NAVI10_META.en.md',
    blurb: '≤4 pasadas. INHIBIT de señuelos. ACTION_REQ. No es chain-of-thought en prosa.',
    blurbEn: '≤4 passes. Decoy INHIBIT. ACTION_REQ. Not chain-of-thought in prose.',
    date: '2026-08-20',
  },
  {
    id: 'navi10-slm',
    title: 'NAVI 10 — SLM de escritorio',
    titleEn: 'NAVI 10 — desktop SLM',
    category: 'navi',
    path: '/docs/navi/NAVI10_SLM.md',
    pathEn: '/docs/navi/NAVI10_SLM.en.md',
    blurb: 'LPU-S ~57 M. Hechos en la CAM. El SLM no rellena cifras duras.',
    blurbEn: 'LPU-S ~57 M. Facts live in the CAM. The SLM does not fill hard figures.',
    date: '2026-08-20',
  },
  {
    id: 'tutorial-monad',
    title: 'Tutorial rxOS 9 SMOKE',
    category: 'tutorial',
    path: '/docs/rxos/tutorial-monad.md',
    blurb: 'Arrancar la ISO 9, tecla v, Navi 7, /prove, cómo medir.',
  },
  {
    id: 'isos',
    title: 'Dónde están las ISOs — rxOS 9',
    category: 'tutorial',
    path: '/docs/rxos/ISOS.md',
    blurb: 'VM para QEMU, metal para USB. SHA-256 de 9.0.0 y cómo flashear.',
  },
  {
    id: 'rxos9',
    title: 'rxOS 9 SMOKE — qué es',
    category: 'tutorial',
    path: '/docs/rxos/RXOS9.md',
    blurb: 'Unikernel Dark Aero, NAVI 7, wget, Photos. El producto ISO de hoy. El 10 es el próximo.',
    blurbEn: 'Dark Aero unikernel, NAVI 7, wget, Photos. Today’s ISO product. 10 is next.',
  },
  {
    id: 'rxos8',
    title: 'rxOS 8 DESKTOP — historia',
    category: 'tutorial',
    path: '/docs/rxos/RXOS8.md',
    blurb: 'Lo que era 8.x. El producto de hoy es 9 SMOKE.',
  },
  {
    id: 'navi-catalog',
    title: 'Catálogo NAVI 1 → 7',
    category: 'navi',
    path: '/docs/navi/CATALOG.md',
    blurb: 'Línea SNN. 7-WORLD es oficial en rxOS 9. 7-NPU (Akida) sigue PLAN.',
  },
  {
    id: 'navi-compare',
    title: 'NAVI frente a otras IA neuromórficas',
    category: 'theory',
    path: '/docs/navi/NAVI_COMPARE.md',
    blurb: 'Loihi, Akida, SpiNNaker, TrueNorth, LLMs. Qué somos y qué no. Para escépticos.',
  },
  {
    id: 'resumen-tecnico',
    title: 'Resumen técnico — lab, web, rxOS, NAVI',
    category: 'theory',
    path: '/docs/rxos/RESUMEN_TECNICO.md',
    blurb: 'Qué dice la web, qué hay en el binario, Q₆, WSP, RX-DIB, estado de la empresa, qué falta y qué sigue.',
  },
  {
    id: 'eternal-eclipse',
    title: 'Eternal Eclipse — hoja de ruta pública',
    category: 'theory',
    path: '/docs/rxos/ETERNAL_ECLIPSE.md',
    blurb: 'Dónde estamos de verdad: 8.5/6.5 medido, 9/7-WORLD en curso. 10/10 es el Eclipse. EchOS es visión.',
  },
  {
    id: 'cianotipo',
    title: 'Cianotipo — rxOS, NAVI, PRISMA, Akida',
    category: 'theory',
    path: '/docs/rxos/CIANOTIPO.md',
    blurb: 'Qué corre, qué está dibujado, qué espera a una placa. Nivel 3 = objetivo.',
  },
  {
    id: 'cianotipo-dummies',
    title: 'Cianotipo para dummies',
    category: 'tutorial',
    path: '/docs/rxos/CIANOTIPO_DUMMIES.md',
    blurb: 'Tres máquinas, un idioma. NAVI 7-WORLD ya corre en rxOS 9. El NPU sigue PLAN.',
  },
  {
    id: 'akida',
    title: 'Akida × rxOS — el gancho',
    category: 'impl',
    path: '/docs/navi/AKIDA.md',
    blurb: 'MetaTF 2.19, Engine C++, HardwareDriver, cinco cerraduras. Sin placa.',
  },
  {
    id: 'navi7',
    title: 'NAVI 7 — 7-WORLD oficial',
    category: 'navi',
    path: '/docs/navi/NAVI7.md',
    blurb: 'Oficial en rxOS 9: catálogo + harvest. 7-NPU Akida sigue PLAN. Sin ficha: DESCONOCIDO.',
  },
  {
    id: 'navi75',
    title: 'NAVI 7.5 — asistente con memoria',
    category: 'navi',
    path: '/docs/navi/NAVI75.md',
    blurb: 'Voz humana, SQLite, Wikipedia/DuckDuckGo. No es un LLM.',
  },
  {
    id: 'navi8',
    title: 'NAVI 8 — context.db',
    category: 'navi',
    path: '/docs/navi/NAVI8.md',
    blurb: '7.5 + SQLite local. Si VERIFY falla, cosecha.',
  },
  {
    id: 'navi88',
    title: 'NAVI 8.8 — supervivencia',
    category: 'navi',
    path: '/docs/navi/NAVI88.md',
    blurb: 'Población de políticas. El malo se duerme. No hay backprop.',
  },
  {
    id: 'navi89',
    title: 'NAVI 8.9 — dual + desk',
    category: 'navi',
    path: '/docs/navi/NAVI89.md',
    blurb: 'Dos voces, TUI, --train --stats, laberinto BFS.',
    date: '2026-08-17',
  },
  {
    id: 'navi92',
    title: 'NAVI 9.2 — zorro',
    category: 'navi',
    path: '/docs/navi/NAVI92.md',
    blurb: 'Una tarea por turno. Resume ≠ Echo. Host LIVE. No ve, no Akida.',
    date: '2026-08-17',
  },
  {
    id: 'navi92-dummies',
    title: 'NAVI 9.2 para dummies',
    category: 'tutorial',
    path: '/docs/navi/NAVI92_DUMMIES.md',
    blurb: 'Zorro, no loro. Cinco comandos slash. Tab completa.',
    date: '2026-08-17',
  },
  {
    id: 'navi92-experts',
    title: 'NAVI 9.2 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI92_EXPERTS.md',
    blurb: 'split_prompt, Echo+RogexWSP, onto, KPI de 32 tests.',
    date: '2026-08-17',
  },
  {
    id: 'navi92-blueprint',
    title: 'Blueprint — pensamiento 9.2',
    category: 'impl',
    path: '/docs/navi/NAVI92_BLUEPRINT.md',
    blurb: 'DAG real: CLI → tarea → VERIFY → render. 10 es otro recuadro.',
    date: '2026-08-17',
  },
  {
    id: 'navi92-train',
    title: 'Entrenar NAVI 9.2',
    category: 'tutorial',
    path: '/docs/navi/NAVI92_TRAIN.md',
    blurb: 'teach-ecosystem, train-social, léxico Echo. No SFT.',
    date: '2026-08-17',
  },
  {
    id: 'echo',
    title: 'Echo — evolución de RogexWSP',
    category: 'wsp',
    path: '/docs/navi/ECHO.md',
    blurb: 'Postal + cubo modal 256/384/320 Hz. Padre: RogexWSP.',
    date: '2026-08-17',
  },
  {
    id: 'navi9-hybrid',
    title: 'NAVI 9 — esqueleto WSP + Q6',
    category: 'navi',
    path: '/docs/navi/NAVI9_HYBRID.md',
    blurb: 'SNN + latente 16 B. LLM solo como boca atada a VERIFY.',
  },
  {
    id: 'navi9',
    title: 'NAVI 9 / 10 — plan',
    category: 'navi',
    path: '/docs/navi/NAVI9.md',
    blurb: 'VERIFY en metal, Q6 retrieve, agente WSP.',
  },
  {
    id: 'setup',
    title: 'Arrancar rxOS 9 — QEMU, VirtualBox, USB',
    category: 'tutorial',
    path: '/docs/rxos/SETUP.md',
    blurb: 'Tres caminos de 2 minutos. ISO VM o metal. NAVI 7.5 en el host.',
  },
  {
    id: 'navi66',
    title: 'NAVI 6.6 — lengua + TUI',
    category: 'navi',
    path: '/docs/navi/NAVI66.md',
    blurb: 'Articulos, tiempos, corrector que supone. TUI de colores. No es un LLM.',
  },
  {
    id: 'navi66-dummies',
    title: 'NAVI 6.6 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI66_DUMMIES.md',
    blurb: 'Si escribes «kien», lo marca y supone «quien».',
  },
  {
    id: 'navi66-experts',
    title: 'NAVI 6.6 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI66_EXPERTS.md',
    blurb: 'Léxico cerrado, Damerau, ratatui / ANSI / pthread.',
  },
  {
    id: 'navi65',
    title: 'NAVI 6.5 — RLC',
    category: 'navi',
    path: '/docs/navi/NAVI65.md',
    blurb: 'Once máscaras G_*. PARSE-RETRIEVE-INFER-VERIFY-RENDER. No es un LLM.',
  },
  {
    id: 'navi65-dummies',
    title: 'NAVI 6.5 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI65_DUMMIES.md',
    blurb: 'Once relés, no un loro. Cinco cajas. DESCONOCIDO si no hay ficha.',
  },
  {
    id: 'navi65-experts',
    title: 'NAVI 6.5 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI65_EXPERTS.md',
    blurb: 'Hook del kernel, math entero, catálogo de código, reflect().',
  },
  {
    id: 'navi6',
    title: 'NAVI 6 — tutor causal',
    category: 'navi',
    path: '/docs/navi/NAVI6.md',
    blurb: 'DAG + world-model + neurogénesis. G_debug de 6.5. No es un LLM ni un QPU.',
  },
  {
    id: 'navi6-dummies',
    title: 'NAVI 6 para dummies',
    category: 'navi',
    path: '/docs/navi/NAVI6_DUMMIES.md',
    blurb: 'El mecánico, no el loro. Analogía de un minuto.',
  },
  {
    id: 'navi6-experts',
    title: 'NAVI 6 para expertos',
    category: 'navi',
    path: '/docs/navi/NAVI6_EXPERTS.md',
    blurb: 'Blob NAVI6W01, do-calculus, hook del kernel, cómo medir.',
  },
  {
    id: 'navi1',
    title: 'NAVI 1 — Q₆ L1',
    category: 'navi',
    path: '/docs/navi/NAVI1.md',
    blurb: 'Hipercubo de 6 bits. 48/48. No habla.',
  },
  {
    id: 'navi5',
    title: 'NAVI 5 — lab cooperativo',
    category: 'navi',
    path: '/docs/navi/NAVI5.md',
    blurb: 'KCC, LIF+STDP, WSP 16 B, air-gap. No es un LLM.',
  },
  {
    id: 'navi5-arch',
    title: 'NAVI 5 — arquitectura',
    category: 'navi',
    path: '/docs/navi/NAVI5_ARCHITECTURE.md',
    blurb: 'Harness pasivo, RX-DIB, Q6, Docker network none.',
  },
  {
    id: 'navi5-train',
    title: 'NAVI 5 — entrenamiento',
    category: 'navi',
    path: '/docs/navi/NAVI5_TRAINING.md',
    blurb: 'Seis fases. Cero pruning. Resultados medidos.',
  },
  {
    id: 'navi45',
    title: 'NAVI-4.5 — el operador',
    category: 'navi',
    path: '/docs/rxos/NAVI45.md',
    blurb: 'WSP 16 B, G_rxos, /prove. No es un LLM.',
  },
  {
    id: 'user-notice',
    title: 'Aviso NAVI 7 — qué esperar',
    category: 'tutorial',
    path: '/docs/rxos/USER_NOTICE.md',
    blurb: 'No es un LLM. 73 fichas. Sin ficha: DESCONOCIDO.',
  },
  {
    id: 'para-curiosos',
    title: 'rxOS 9 para curiosos',
    category: 'demo',
    path: '/docs/rxos/para-curiosos.md',
    blurb: 'Tres minutos. Arrancas, pulsas v, preguntas.',
  },
  {
    id: 'demostracion',
    title: 'Demostración y benches rxOS 9',
    category: 'demo',
    path: '/docs/rxos/demostracion.md',
    blurb: '9 SMOKE + RAPL metal 8.5. Capturas QEMU reales.',
  },
  {
    id: 'monad-demo',
    title: 'Spec de demo dual',
    category: 'demo',
    path: '/docs/rxos/MONAD-DEMO.md',
    blurb: 'Público curioso + métricas para quien mide.',
  },
  {
    id: 'hp-metal-85',
    title: 'HP 15-ac195nl — metal 8.5 medido',
    category: 'bench',
    path: '/docs/rxos/HP_AC195NL_85.md',
    blurb: 'RAPL, navi3/navi6, 72.5 µJ/run Q6. Ocho fotos del portátil, 17 ago 2026.',
  },
  {
    id: 'measure',
    title: 'MEASURE — cómo medir Q₆ / L2',
    category: 'bench',
    path: '/docs/navi/MEASURE.md',
    blurb: 'Protocolo de medida del banco host NAVI. Metal: /docs/hp-metal-85.',
  },
  {
    id: 'l2',
    title: 'NAVI L2 — HDC + RWKV',
    category: 'bench',
    path: '/docs/navi/L2.md',
    blurb: '66 352 B planos, leaky 7:1, no es un LLM.',
  },
  {
    id: 'l3',
    title: 'NAVI L3 — entrenar el SLM',
    category: 'bench',
    path: '/docs/navi/L3.md',
    blurb: 'train.py → navi2_weights.bin, sin Hugging Face.',
  },
  {
    id: 'rfc-q6',
    title: 'RFC-2026-08-Q6 — PoC medido',
    category: 'theory',
    path: '/docs/navi/RFC-2026-08-Q6.md',
    blurb: 'Hipercubo Q₆, Hamming, codebook [6,3,3]. Lo que ya corre.',
  },
  {
    id: 'rfc-q6-campana',
    title: 'RFC-2026-08-Q6 — campaña abierta',
    category: 'research',
    path: '/docs/navi/RFC-2026-08-Q6-CAMPANA.md',
    pdf: '/docs/navi/RFC-2026-08-Q6_CAMPANA.pdf',
    blurb: 'Convocatoria: hipótesis Q₆, fases, KPI y dónde enviar resultados.',
  },
  {
    id: 'manifesto',
    title: 'Manifiesto neuromórfico',
    category: 'theory',
    path: '/docs/rxos/neuromorphic_manifesto.md',
    blurb: 'Eventos, LIF entero, límites del slogan.',
  },
  {
    id: 'event-fabric',
    title: 'Event fabric',
    category: 'theory',
    path: '/docs/rxos/event_fabric.md',
    blurb: 'Anillos SPSC, actores blandos, Q16.16.',
  },
  {
    id: 'monad',
    title: 'rxOS MONAD — mapa de código',
    category: 'research',
    path: '/docs/rxos/MONAD.md',
    blurb: 'Dónde está el código y cómo comprobarlo.',
  },
  {
    id: 'navi3',
    title: 'NAVI-3/4 WSP — arquitectura',
    category: 'navi',
    path: '/docs/rxos/NAVI3_WSP_ARCHITECTURE.md',
    blurb: 'Transductor S→S′, 16 B, máscara ES, ext v0.5.',
  },
  {
    id: 'navi2',
    title: 'NAVI 2 — arquitectura (legado ASCII)',
    category: 'navi',
    path: '/docs/rxos/NAVI2_ARCHITECTURE.md',
    blurb: 'Motor de bytes legado. El chat del ISO usa NAVI-3.',
  },
  {
    id: 'kernel-navi',
    title: 'kernel/navi README',
    category: 'impl',
    path: '/docs/navi/kernel.md',
    blurb: 'Actor blando Q₆ en el unikernel.',
  },
  {
    id: 'prisma-engine',
    title: 'PRISMA Engine técnico',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_ENGINE_TECHNICAL.md',
    blurb: 'Runtime Rust: SPSC, Δ-mod, LIF AVX2.',
  },
  {
    id: 'prisma5-snn',
    title: 'PRISMA 5 SNN',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_SNN_TECHNICAL.md',
    blurb: 'Producto SNN event-driven (sin descarga P5).',
  },
  {
    id: 'prisma5-roadmap',
    title: 'PRISMA 5 roadmap',
    category: 'prisma',
    path: '/docs/prisma/PRISMA_5_ROADMAP.md',
    blurb: 'Fases α → 1.0 y gates de release.',
  },
  {
    id: 'wsp-readme',
    title: 'RogexWSP — protocolo',
    category: 'wsp',
    path: '/docs/wsp/README.md',
    blurb: 'Un núcleo de significado, muchas máscaras. Repo navywakura/RogexWSP.',
  },
  {
    id: 'wsp-philosophy',
    title: 'RogexWSP — filosofía',
    category: 'wsp',
    path: '/docs/wsp/PHILOSOPHY.md',
    blurb: 'I+E→S. La palabra es solo una máscara.',
  },
  {
    id: 'wsp-spec',
    title: 'RogexWSP — SPEC v0.1',
    category: 'wsp',
    path: '/docs/wsp/SPEC.md',
    blurb: '32 átomos, 6 ejes, JSON y binario normativo.',
  },
  {
    id: 'wsp-binary',
    title: 'RogexWSP — formato binario',
    category: 'wsp',
    path: '/docs/wsp/BINARY_FORMAT.md',
    blurb: 'Magic WSP, flags, átomos 5-bit, emoción i8.',
  },
  {
    id: 'wsp-snippets',
    title: 'RogexWSP — snippets',
    category: 'wsp',
    path: '/docs/wsp/SNIPPETS.md',
    blurb: 'primitives, Emotion, Symbol, encode/decode. Código real.',
  },
];

export function catById(id) {
  return DOC_CATEGORIES.find((c) => c.id === id) || null;
}

export function docById(id) {
  return DOCS.find((d) => d.id === id) || null;
}

export function docDate(d) {
  return d.date || '2026-08-17';
}

export function docByPath(pathname) {
  const clean = pathname.replace(/\/+$/, '');
  return DOCS.find((d) => d.path.replace(/\.md$/, '') === clean || d.path === clean) || null;
}

export function docTitle(d, lang = 'es') {
  return lang === 'en' && d.titleEn ? d.titleEn : d.title;
}

export function docBlurb(d, lang = 'es') {
  return lang === 'en' && d.blurbEn ? d.blurbEn : d.blurb;
}

export function docPath(d, lang = 'es') {
  return lang === 'en' && d.pathEn ? d.pathEn : d.path;
}

export function catLabel(cat, lang = 'es') {
  if (!cat) return '';
  return lang === 'en' && cat.labelEn ? cat.labelEn : cat.label;
}

export const FEATURED_DOC_IDS = [
  'diario',
  'navi10-spec',
  'navi10',
  'rxos10',
  'navi10-lpu',
  'navi10-ship',
  'navi10-train',
  'setup',
  'isos',
];
